# Generated by Django 2.1.2 on 2020-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20181204_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited_term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=1, null=True),
        ),
    ]
